name: Adam Rasheed
description: Front-end Developer
image: /assets/Adam-Rasheed-Pano-web@2x.jpg
tagline: I’m a Front-end Developer based in Southern California.

email: adamrasheed91@gmail.com
resume: https://www.dropbox.com/s/55xlzhq0tq63bn8/Adam-Rasheed-CV-Dev-2017.pdf?dl=0

url: https://adamrasheed.com


markdown: redcarpet
highlighter: pygments # or rouge or null
include: ['case-studies']
exclude: ["node_modules", "gulpfile.js", "package.json"]

plugins:
  - jekyll-sitemap
